openapi: 3.0.0
info:
  title: 2 - Games
  version: '1.0'
  contact:
    name: Eyecu.Digital
servers:
  - url: 'https://games.eyecu.digital'
    description: EyeCu Games Servers
paths:
  /api/category:
    get:
      summary: Get categories list
      responses:
        '200':
          description: Success categories list returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 169
                        title:
                          type: string
                          example: New
                        parent:
                          type: integer
                          example: 0
                        position:
                          type: integer
                          example: 1
                        href:
                          type: string
                          example: hot
                        shop_id:
                          type: integer
                          example: 8
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      per_page:
                        type: integer
                      last_page:
                        type: integer
                      next_page_url:
                        type: string
                      prev_page_url:
                        type: string
                      from:
                        type: integer
                      to:
                        type: integer
              examples:
                Categories list:
                  value:
                    data:
                      - id: 169
                        title: New
                        parent: 0
                        position: 1
                        href: hot
                        shop_id: 8
                    meta:
                      total: 0
                      per_page: 0
                      last_page: 0
                      next_page_url: string
                      prev_page_url: string
                      from: 0
                      to: 0
        '401':
          description: Unauthorized
      operationId: get-api-categories
      description: Get list of categories available
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: API Key of the Shop
          required: true
        - schema:
            type: string
          in: query
          name: shop_id
          description: Shop ID
          required: true
      tags:
        - Global data
      security:
        - JWT Token: []
  /api/games:
    get:
      summary: Get games list
      responses:
        '200':
          description: Success games list returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        title:
                          type: string
                        category:
                          type: array
                          items:
                            type: string
                        device:
                          type: string
                        denomination:
                          type: string
                        view:
                          type: string
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      per_page:
                        type: integer
                      last_page:
                        type: integer
                      next_page_url:
                        type: string
                      prev_page_url:
                        type: string
                      from:
                        type: integer
                      to:
                        type: integer
        '401':
          description: Unauthorized
      operationId: get-api-games
      description: |-
        Get list of games available

        This is the list of the available games : https://docs.google.com/spreadsheets/d/11AmYOKU3cY6sVo1hsboj-xVf-1ig2hqNugeDa_yHC6I/edit#gid=0
        
        If you want to use our CDN for the games picture, this is the method : 
        
        http://eyecu-games-pictures.b-cdn.net/games/{GAME_NAME}.jpg
        
        (Ex : http://eyecu-games-pictures.b-cdn.net/games/AdmiralNelsonAM.jpg)
        
        For the device property : 
           - 0 => Mobile only
           - 1 => Desktop only
           - 2 => Mobile + Desktop
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: API Key of the Shop
          required: true
        - schema:
            type: string
          in: query
          name: shop_id
          description: Shop ID
          required: true
      security:
        - JWT Token: []
      tags:
        - Global data
  /api/login:
    post:
      summary: Data access authentication
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              examples:
                Login success:
                  value:
                    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vdGVzdGluZy5sdWNreS1zdHJpa2UuY2x1Yi9hcGkvbG9naW4iLCJpYXQiOjE1OTY1MzcwNDQsImV4cCI6MTU5NjU0MDY0NCwibmJmIjoxNTk2NTM3MDQ0LCJqdGkiOiIyS0V2RXVMckM3bTY2aW9VSURvME1kdEtHckkxT3FmaTBXdVJwOHVWIiwic3ViIjo2NywicHJ2IjoiM2VmNmNmODlmNTU5YTkyYjNlYjdiNzdiOGM3MmRiMzlkNDdlZGI2MCJ9.XaTpLVWTJaSCfT93I8AKACdMGNfGAjAyu3oAHFyoVW4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Invalid credentials:
                  value:
                    error: Invalid credentials.
      operationId: post-api-login
      description: To communicate with our API, you should login as a user to proof your identity. You can use the Admin User given by us.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            examples: {}
        description: |-
          Authentication request require only 2 parameters : 
          - username : username of the user
          - password : password of the user
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: API Key of the shop
          required: true
        - schema:
            type: string
          in: query
          name: shop_id
          description: Shop ID
          required: true
      tags:
        - Global data
    parameters: []
components:
  schemas: {}
  securitySchemes:
    JWT Token:
      type: http
      scheme: bearer
      description: Provided by /api/login
tags:
  - name: Global data
