openapi: 3.0.0
info:
  title: Games
  version: '1.0'
  contact:
    name: Eyecu.Digital
servers:
  - url: 'https://games.eyecu.digital'
    description: EyeCu Games Servers
paths:
  /api/category:
    get:
      summary: Get categories list
      responses:
        '200':
          description: Success categories list returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 169
                        title:
                          type: string
                          example: New
                        parent:
                          type: integer
                          example: 0
                        position:
                          type: integer
                          example: 1
                        href:
                          type: string
                          example: hot
                        shop_id:
                          type: integer
                          example: 8
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      per_page:
                        type: integer
                      last_page:
                        type: integer
                      next_page_url:
                        type: string
                      prev_page_url:
                        type: string
                      from:
                        type: integer
                      to:
                        type: integer
              examples:
                Categories list:
                  value:
                    data:
                      - id: 169
                        title: New
                        parent: 0
                        position: 1
                        href: hot
                        shop_id: 8
                    meta:
                      total: 0
                      per_page: 0
                      last_page: 0
                      next_page_url: string
                      prev_page_url: string
                      from: 0
                      to: 0
        '401':
          description: Unauthorized
      operationId: get-api-categories
      description: Get list of categories available
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: API Key of the Shop
          required: true
        - schema:
            type: string
          in: query
          name: shop_id
          description: Shop ID
          required: true
      tags:
        - Global data
      security:
        - JWT Token: []
  /api/games:
    get:
      summary: Get games list
      responses:
        '200':
          description: Success games list returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        title:
                          type: string
                        category:
                          type: array
                          items:
                            type: string
                        device:
                          type: string
                        denomination:
                          type: string
                        view:
                          type: string
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      per_page:
                        type: integer
                      last_page:
                        type: integer
                      next_page_url:
                        type: string
                      prev_page_url:
                        type: string
                      from:
                        type: integer
                      to:
                        type: integer
        '401':
          description: Unauthorized
      operationId: get-api-games
      description: |-
        Get list of games available

        This is the list of the available games : https://docs.google.com/spreadsheets/d/11AmYOKU3cY6sVo1hsboj-xVf-1ig2hqNugeDa_yHC6I/edit#gid=0
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: API Key of the Shop
          required: true
        - schema:
            type: string
          in: query
          name: shop_id
          description: Shop ID
          required: true
      security:
        - JWT Token: []
      tags:
        - Global data
  '/launcher/{game}/{token}/{mode}':
    parameters:
      - schema:
          type: string
          example: CorridaRomanceWD
        name: game
        in: path
        required: true
        description: Game name
      - schema:
          type: string
          example: Hf4h08gf87e8z70ef8zf7ze89f
        name: token
        in: path
        required: true
        description: User token (JWT / Seamless token)
      - schema:
          type: string
          example: desktop
        name: mode
        in: path
        required: true
        description: Game mode (desktop or mobile)
    get:
      summary: Start a game session for the user
      tags:
        - Game session
      responses:
        '307':
          description: |-
            Temporary Redirect

            Redirect automaticly to the game
      operationId: get-launcher-game-token-mode
      description: |-
        This is not an API endpoint ! You should redirect the user (or serve it in an iframe) using this syntax.

        https://games.eyecu.digital/launcher/{game}/{token}/{mode}

        Games name = from /api/games => use the 'name' property of the game (not the title)

        Token = From /api/login or if you want to use seamless, check the seamless part for token generation

        Mode = desktop or mobile

        ### /!\ Information for the lobby url /!\
        You can add the lobby url with : ?lobby_url={lobby_url} at the end

        For exemple :

        /launcher/NarcosNET/JWT_TOKEN/desktop?lobby_url=https://www.google.com (You need to write the full url with https://, http://)

        If you don't provide the lobby url, it will take by default the lobby_url enter in your shop admin configuration (default lobby url).

        If you pass the lobby url in the api when you start a game, it will prioritize it.
components:
  schemas: {}
  securitySchemes:
    JWT Token:
      type: http
      scheme: bearer
      description: Provided by /api/login
tags:
  - name: Global data
  - name: Game session
